kind: pipeline
name: default

steps:

- name: publish
  image: plugins/docker
  settings:
    repo: viant/drone-gcloud2
    username: replicant0wnz 
    password:
      from_secret: docker_password
    tags:
      - latest
      - 1.0.${DRONE_BUILD_NUMBER}

- name: notify
  image: plugins/slack
  settings:
    room: devops
    webhook:
      from_secret: webhook
